### ISSUE TITLE
Location Information

### ISSUE THREAD

**Issue by CodyStringham** [CodyStringham/fictionist#11]
See "Efforts"

We can get this from new users who have been invited when they set a password. This could also just be added to our registration process, also taking into account the omniauth process.

How do we want to handle this as far as data? Maybe Andrew will have more insight ( postal code vs closest city the band performs in regularly )

**Comment by QuintinAdam** [comment]
Probably just get there zipcode. From that we can get city/state. 

Does facebook/twitter give zipcode by chance?

**Comment by CodyStringham** [comment]
Facebook will sell us their souls, but Twitter doesn't even ask you for that when creating an account. This also assumes they gave one to Facebook, i'm not sure you are required to.

I think the safer option is just collecting it ourselves.

**Comment by CodyStringham** [comment]
:preferred_location stored on User
