### ISSUE TITLE
Content Uploader

### ISSUE THREAD

**Issue by QuintinAdam** [CodyStringham/fictionist#2]

**Comment by QuintinAdam** [comment]
Should have the ability for the band to upload/edit content and display it in a kewl way. 

Should be able to upload:

- Photos
- PDF's(maybe) ex. for sheet music
- Music
- or attach a youtube link.
- or just text

**Comment by QuintinAdam** [comment]
Additionally we could have tags, favorites, and comments.

Which could all be polymorphic models.

**Comment by QuintinAdam** [comment]
Content should have 
- attachment
- attachment type
- location
- text
- belongs to user (uploaded by brand member)

**Comment by KatherineMuedas** [comment]
I'll start working on this. :smiley:

**Comment by KatherineMuedas** [comment]
I've added two commits for this feature:
 
6f188b91f50a452738616a9b5ac92049478db052

db2d1776e923ae31ab9c7db81c2f61867a55ca03

**Comment by CodyStringham** [comment]
This has been changed to include an `:uploader_id`, users now have `:uploaded_contents` and `:purchased_contents, through: :redemptions`

**Comment by QuintinAdam** [comment]
any thoughts on how we want to display the content. Maybe just to start use masonry? or an alternative.

**Comment by QuintinAdam** [comment]
oh never mind you already started adding a grid.

**Comment by CodyStringham** [comment]
yeah but that was super quick and dirty, just so I could see it working with unlocks. I haven't looked into anything but masonry would probably be cool, i'm open to anything
